travis:
  secure:
    BINSTAR_TOKEN: l3659jEm2pn0SFB0+5uTS31Jqdc3/zvdv4EUdseZJpOsCPOeaq1BjwZnONQt2bGzWiLVJCxzWQyWBVk1eJI6LZ8UNj1DG3v4gs7eWOz6OZspTj02yEp7PDTEv7YavyMgIXgL8IlGdpdIiMBC1cE46jq8MADa4avxJNDMvhk7Vq073qbhfBdg21c5aWvtmEHodfNg6BpCreJh27bVVGAMmSbCz34fe90RQCZwvnchEEUt5oSDLdMh2dn0Mwo8/wcYPKUgSqJqrCAIy/mnHmJryqKW05WVtWRTAYFqryRynn8zuuaAzuTLdfaNC+dVL8FU5h7da8Bk9/N8s7iSWX+Y/YWSArGXc+vgtQRK4eKZGvptgOfWXW1tHqK8uL6necnEoR8CC4Pt0pkPw+h0BJl3lPS51WN4aCcRuTpcPJOY80mAjLTVlGZkTXLpfVHAsISZflJEtsbyBBoYBZ0w7wgL1B0xw+I6APASuIUzSx56x8VO10Ls8FKaUogJihk57w6uwqEp53ga8ltCfCvvmTyT/SRx8AAafQT1TI3OfbZbwki8wZrt4ENPDEWoj6ovtHCg440wGt7mUDq3vNa5wcb6DH0uNPp4CfTsYzuRVt2/RQaXeh/YnBcVc/m1R2DIdtYE5hL6b67T1OG5wZfu2ATDbkT290GMU3JHy2tz+HZe/zs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
