travis:
  secure:
    BINSTAR_TOKEN: ChFpDdo5qdmsO0Y34FOYHMR+diF3/t5Yn2M6XyJpbKEhT4qLmGqNByhDcSoZnZ6xAsH2uPwpmdvSWWAw8SFXm3MiHjvunuIx55UaFxZ+N3nUya7y2e3ewong35TDS/RvzwePFNOIWqW1Vnxg+GybqYalnX8VnKreF/BaWfn3sMR/dk9WK4ivMnMYTtHJ2uzkMUkjoIEdM9Tnnci/BOMpLmNGhohsvK8n8ur5EdsCt3+0X1Q9D7zHOUUtI2ocKsEIpUs9fGzYhxtmkTFMZOIC5PjByDw+LcFSlZw1o/9G2OJN+6f+Xz6d9W4tCw6M246KcPoJJhvEMUAdAWJmsw7/lZiEjNQnPRFPeTYywhpIs2vT+XJ62VEV9U9nk2OHC30nM3EIQD85WX4Sh+rJ2+kqnWvcfq6UIS0RQN9sXQGmd357s7pO2kccaGWbFcMP0oeykiCnI1ErWw9jm+44wI7UC1XwVQhcz36phol+fqC949z7nwJcZUf69VUE0Vy2MrfD+8a3ncqUIpsew3hzSKwCzc4rRlVvXhVThnwE8BIko/qtiithyRVXWVMPF3IiMPw2wml5kzEnPyEhPkuEivaIGTXQOslyMd01Ts67whYn0g/XF6z6rW8Te9hw80UYm/o4jAOpRf1zhzzNC0Yy9pELmyghE6u70P5/v+x6BRlycpY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
